### PR TITLE
Works in Node.js & Express, Filled Out README

### PR DESCRIPTION
**Pull request by chrisjpowers**
I wanted to try using Facile on the server, so I updated it to work as an npm module. It's Express compatible (which just means that `facile.compile` returns a compiler function) and the README has been filled out and updated accordingly.

I have not published the package to the NPM registry, as I figured you would want to have ownership of that.

### CODE REVIEW

**Comment by EndangeredMassa** [comment]
Hah! I was literally going to do this exact thing this week. I am going to present the node version at the meetup next week. 

So, thanks for taking care of that. I'll take a deeper look later, but it looks awesome so far.

**Comment by chrisjpowers** [comment]
I found that I didn't get very far using Facile before I wanted to be able to use "deferred" function values in my data object that would be run at render-time. Once that was in place, I needed the ability to make those functions asynchronous, so I reworked the lib to support both sync and async flows. Take a look near the bottom of the README for examples.

**Comment by EndangeredMassa** [comment]
I'm not convinced of the need for deferred values or asynchrony. I've used facile extensively without the need for either. In general, if I wanted to call a method at render time, I'd call it just before calling `facile(template, updatedData)`.

Do you have a specific use case where deferred values are necessary? Or, is this a consequence of how you're using it in Node.js?

**Comment by chrisjpowers** [comment]
I think the use case (which I could understand you not deeming valid) is me wanting to use a smarter presenter object or model in Facile rather than a simple data object. For example, I wanted to drop a Resourceful object in as a Facile data object, and I had methods on that object that I wanted accessible as well as the properties. This still doesn't work right now, however, because Facile will currently iterate over all properties, run all the functions (including #save, whoops) and then render. I'm going to try updating Facile so that it only runs deferred methods when there is a matching element.

All that to say, I'm not sure whether this is a valid use case, I'm still playing with it. I could create a presenter that generates a Facile data object, rather than being dropped into Facile itself, and all the async stuff could be managed in the presenter.

Feel free to not merge the async code in; I'll keep playing with it and let you know if I find some more compelling use cases.

**Comment by EndangeredMassa** [comment]
I can see wanting to use something like a Resourceful object directly, but I think it makes facile too smart.

That's exactly how we use facile: have the presenter create the object that facile expects.

Can you actually split this PR into two separate PRs so that I can merge in the node support without the defer/async, for now?

**Comment by chrisjpowers** [comment]
Unfortunately Github doesn't let you do that, so I will close this pull request, make a new branch without the async feature and then do a new pull request with that branch.

**Pull request closed without merging**
